import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import Navbar from "../components/Navbar";
import Providers from "../components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Digital Hippo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn("relative h-full font-sans antialiased", inter.className)}
			>
				<Providers>
					<Navbar />
					<main className="relative flex flex-col min-h-screen">
						<div className="flex-grow flex-1">{children}</div>
					</main>
				</Providers>
			</body>
		</html>
	);
}
